apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: button.nandy.io
spec:
  namespace: button-nandy-io
  description: Button - Nandy I/O
  manifests:
  - path: kubernetes/namespace.yaml
  - path: daemon/kubernetes/daemon.yaml
  requires:
  - name: redis.klot.io
    source:
      site: github.com
      repo: klot-io/redis
  settings:
  - name: button
    description: Where there is a button attached
    multi: true
    node: enabled
