apiVersion: klot.io/v1
kind: App
metadata:
  name: button.nandy.io
  description: Button - Nandy I/O
spec:
  source:
    site: github.com
    repo: nandy-io/button-daemon
  manifests:
  - path: kubernetes/namespace.yaml
  - path: kubernetes/daemon.yaml
  requires:
  - site: github.com
    repo: klot-io/redis
  labels:
  - name: button
    description: Where there is a button attached
    value: enabled
