apiVersion: klot.io/v1
kind: App
metadata:
  name: button.nandy.io
  version: v0.1
  description: Button - Nandy I/O
spec:
  namespace: button-nandy-io
  manifests:
  - path: kubernetes/namespace.yaml
  - path: daemon/kubernetes/daemon.yaml
  requires:
  - name: redis.klot.io
    source:
      site: github.com
      repo: klot-io/redis
  labels:
  - name: button
    description: Where there is a button attached
    value: enabled
