apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon
  namespace: button-nandy-io
spec:
  template:
    spec:
      containers:
      - name: daemon
        image: daemon-button-nandy-io
        imagePullPolicy: Never
        command: ["tail", "-f", "/dev/null"]
        env:
        - name: LOG_LEVEL
          value: WARNING
