apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon
  namespace: button-nandy-io
  labels:
    app: daemon
spec:
  selector:
    matchLabels:
      app: daemon
  template:
    metadata:
      labels:
        app: daemon
    spec:
      nodeSelector:
        button.nandy.io/button: enabled
      volumes:
      - name: dev-i2c-1
        hostPath:
          path: /dev/i2c-1
      - name: sys-class-gpio
        hostPath:
          path: /sys/class/gpio
      - name: sys-devices
        hostPath:
          path: /sys/devices
      containers:
      - name: daemon
        image: docker.io/nandyio/button-daemon:0.1
        imagePullPolicy: Always
        env:
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: REDIS_HOST
          value: db.redis-klot-io
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: nandy.io/button
        - name: GPIO_PORT
          value: "4"
        - name: SLEEP
          value: "0.1"
        volumeMounts:
        - mountPath: /dev/i2c-1
          name: dev-i2c-1
        - mountPath: /sys/class/gpio
          name: sys-class-gpio
        - mountPath: /sys/devices
          name: sys-devices
        securityContext:
          privileged: true
